name: 'Branch Protection Check'
on:
  pull_request:
    branches: [main]

jobs:
  check_source_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Validate source branch
        run: |
          SOURCE_BRANCH="${{ github.head_ref }}"

          case "$SOURCE_BRANCH" in
            "develop")
              echo "✅ Regular deployment from develop"
              ;;
            hotfix/*)
              echo "🚨 Hotfix deployment: $SOURCE_BRANCH"
              echo "::warning::This is a hotfix deployment - ensure proper review"
              ;;
            *)
              echo "❌ ERREUR: Seules 'develop' et 'hotfix/*' peuvent merger vers main"
              echo "Pour les features: feature/* → develop → main"
              echo "Pour les hotfixes: hotfix/* → main"
              exit 1
              ;;
          esac
